services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
    links:
      - database:db
  dbadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=hackRPIX
    volumes:
      - ./dbadmin:/var/lib/pgadmin:z
    depends_on:
      - database
  database:
    image: postgres:latest
    ports: 
       - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data:z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=hackRPIX