services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - database:db
  database:
    image: postgres:latest
    ports: 
       - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=hackRPIX
  dbadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=hackRPIX
    volumes:
      - ./dbadmin:/var/lib/pgadmin
    depends_on:
      - database